# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbdb88e0a1de165a42c283daae6cec4fe2ac5153b2ab61d92ce4011f1f03ad9d3d8744d954463dc018d9459808a318d369600ac76de9429724adc9e5fc528300

test:
  secret_key_base: 69ba7d7d88c000c64b88e9d7f01c4a7b958057e48655af1166326dab13480ad0fe0a3eb1594bfa952dcc50aca603b6eac193fd94922e1bd6613196e6269173cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
